### ISSUE TITLE
关于特征值的选取

### ISSUE THREAD

**Issue by leezivin** [luoyetx/JDA#12]
按照3000fps的思路，每一颗树在训练的时候特征值提取的两个点都是在同一个lanmark_id的某一个radius内生成的，但是我看你的代码在获取特征值的时候又是随机生成了两个landmark_id，在函数Cart::GenFeaturePool里面。
这里有点疑惑，希望解答下。谢谢

**Comment by luoyetx** [comment]
这里计算 shape-index feature 的方式跟 3000fps 中有点不一样，具体可以参照[论文](http://research.microsoft.com/en-US/people/yichenw/eccv14_jointdetectalign.pdf)的 section 4.2

**Comment by leezivin** [comment]
谢谢你的回复
文中section 4.2只说了用pixel difference feature，既然整个框架和3000fps的框架一样，所以我觉得取特征值的方式应该也和3000fps一样，这样也更能体现3000fps里面提到的先局部再整体的思想，而不是使用ESR提取特征的方式。

**Comment by luoyetx** [comment]
@leezivin 不是的，论文中明确写了怎么计算 shape-index feature 的，请仔细阅读=。=
![tlsb f2h xv z x5zl o8m](https://cloud.githubusercontent.com/assets/2768843/11087203/5d834090-8893-11e5-9e60-c9ec21692ffc.png)

**Comment by leezivin** [comment]
看到了，谢谢！
