### ISSUE TITLE
The variance of residual when create regression node 

### ISSUE THREAD

**Issue by huneng** [luoyetx/JDA#15]
There is calculating the max variance of residuals in your code, I think it should be min. So why you did that ? An could you send me your best fddb roc curves to me, huneng1991@163.com.

**Comment by luoyetx** [comment]
Yes, it should be the minimum variance, so I calculate the maximum reduction of variance.

For the ROC curves, sorry, As the README said, I didn't have a fully trained model yet. It's very tough.

If you are interested in JDA, you can join the QQ group mentioned in README. welcome~

**Comment by huneng** [comment]
Thinks.
