### ISSUE TITLE
ptr[j] = img.at<uchar>(x1_, y1_) - img.at<uchar>(x2, y2); 这行代码

### ISSUE THREAD

**Issue by GarrickLin** [luoyetx/JDA#2]
[JDA/src/jda/data.cpp](https://github.com/luoyetx/JDA/blob/dev/src/jda/data.cpp) 中的第57行代码
`tr[j] = img.at<uchar>(x1_, y1_) - img.at<uchar>(x2, y2);`
是不是应该改成
`tr[j] = img.at<uchar>(x1_, y1_) - img.at<uchar>(x2_, y2_);`

**Comment by luoyetx** [comment]
确实写错了
