### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by foresttserof** [luoyetx/JDA#20]
你好，我看到前面的提问中你有提到用标注五个关键点的10000个人脸和20000张非人脸进行训练，大概的训练耗时需要多久，检测人脸效果和五官标注的效果如何

**Comment by luoyetx** [comment]
5 个点的效果太差，建议用更多的点

**Comment by foresttserof** [comment]
谢谢你的回答，我正在学习你的代码，觉得detectMultiScale()函数里for循环应该也对shapes_里的每个元素乘上scale

**Comment by luoyetx** [comment]
detectMultiScale() 给出的 shape 是相对值，应该在 0~1 之间，但是人脸框确实是通过 scale 计算回原图的位置了，shape 会在后面的 Detect() 中会还原到原图上
