### ISSUE TITLE
a question about the omp_set_num_threads()

### ISSUE THREAD

**Issue by tornadomeet** [luoyetx/JDA#25]
hello, @luoyetx 
just as the 2 line:https://github.com/luoyetx/JDA/blob/master/src/jda/data.cpp#L886-L887
the first line get  threads_n, which is the max num threads we can use, so why set it 3 times larger in the next line? i think it  may be no meaning, just equals `omp_set_num_threads(threads_n);` ( i'm not  familiar with openmp),thanks.

**Comment by luoyetx** [comment]
Hi, @tornadomeet 
setting 3*thread_n to load the images can reduce the time.

**Comment by tornadomeet** [comment]
Thanks. It's so strange! because it will be larger than the number of logic threads in the machine.

**Comment by luoyetx** [comment]
@tornadomeet I think the shortcoming of loading images is the IO operations not the data processing. So, more threads may give you a better performance.
