### ISSUE TITLE
neg data set

### ISSUE THREAD

**Issue by jayachandrad** [luoyetx/JDA#26]
Hi,

For non-face images, the resized images are stored in neg.hds. However, during the training, neg.CalcFeatureValues() is trying to access neg.imgs, neg.imgs_half and neg.imgs_quarter which are not initialized.

For me it looks like a bug. Please correct me if I am missing any thing here.

Thanks and Regards,

**Comment by luoyetx** [comment]
@jayachandrad `neg.hds` is optional, they are non-face patches not the background images. We always need background images to mining hard negative samples. Actually, when the program starts, we first load face images and background images to `pos.imgs` and `neg.imgs`, then, if there's an optional initial negative samples which are manually prepared, we load these images to `neg.hds` and will use them to mining hard negative samples at first.

**Comment by jayachandrad** [comment]
@luoyetx, Thank you very much. Sorry for not paying attention to details in the readme file you have provided. Best regards.
