### ISSUE TITLE
About main.cpp

### ISSUE THREAD

**Issue by 0722WonJun** [luoyetx/JDA#29]
Hello.

When I was using your source code, I had an question in the main.cpp

I wonder why there is a N have to be 10?(Line 22)

![image](https://cloud.githubusercontent.com/assets/24996806/21755403/a3a2460e-d656-11e6-87bb-30cf2d9176f4.png)

Is there any reason?

I'm looking forward to your reply. Thanks very much.

**Comment by luoyetx** [comment]
run n times to calculate the average running time.
