### ISSUE TITLE
there might be a mistake

### ISSUE THREAD

**Issue by GarrickLin** [luoyetx/JDA#4]
in [JDA/src/jda/btcart.cpp](https://github.com/luoyetx/JDA/blob/dev/src/jda/btcart.cpp) line 40

```
cart.Initialize(stage, k);
```

might be

```
cart.Initialize(stage, landmark_id);
```

**Comment by luoyetx** [comment]
@GreenKing Thanks for pointing this mistake out, it will be fixed in the next commit.
