### ISSUE TITLE
How many landmarks does a feature need?

### ISSUE THREAD

**Issue by GarrickLin** [luoyetx/JDA#5]
在您的博客中有这样一句话

```
在 3000fps 中，由于随机森林是针对单个关键点的，所有随机树中使用到的特征点不会关联到其他关键点上，只在当前关键点的附近区域随机产生两个特征点，做像素差值来作为 Shape-index 特征。
```

另外在原文`3000fps`的section 3.3中提到

```
1) ...
2) we only consider the pixel features in the local region of a landmark 
```

上述都表明在文章`3000fps`中的做法是在训练一个landmark的cart的时候，只用了它本身附近的shape-index特征
但是在您的代码中，Feature是包含有两个landmark_id的，请问这样做的原因是什么呢？

**Comment by GarrickLin** [comment]
I'm sorry. I found the point in `section 4.2 Joint Learning of Detection and Alignment` of `JDA`.

**Comment by luoyetx** [comment]
3000fps and JDA use different methods of feature extraction, we can also try [RCPR](http://www.vision.caltech.edu/xpburgos/ICCV13/)'s way.
